DROP TABLE IF EXISTS UTILITY_PAYMENT;
DROP TABLE IF EXISTS BILL_PAYMENT;
DROP TABLE IF EXISTS BILL;
DROP TABLE IF EXISTS TRANSACTION;
DROP TABLE IF EXISTS MORTAGE_DETAIL;
DROP TABLE IF EXISTS SAVING_DETAIL;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS OTP;
DROP TABLE IF EXISTS EKYC;
DROP TABLE IF EXISTS USER_BIOMETRIC;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
   USER_ID varchar(10) NOT NULL,
   FULL_NAME text,
   EMAIL text,
   PHONE text,
   ROLE text,
   CREATED_AT datetime,
   IS_ACTIVE bool,
   PASSWORD text,
   PRIMARY KEY (USER_ID)
);

CREATE TABLE ACCOUNT (
   ACCOUNT_ID varchar(10) NOT NULL,
   USER_ID varchar(10),
   ACCOUNT_TYPE text,
   BALANCE float,
   INTEREST_RATE float,
   CREATED_AT datetime,
   STATUS text,
   ACCOUNT_NUMBER char(10),
   PRIMARY KEY (ACCOUNT_ID)
);

CREATE TABLE EKYC (
   EKYC_ID varchar(10) NOT NULL,
   USER_ID varchar(10),
   IMG_FRONT_URL text,
   IMG_BACK_URL text,
   SELFIE_URL text,
   STATUS text,
   REVIEWED_AT varchar(30),
   REVIEWED_BY varchar(30),
   CREATED_AT datetime,
   PRIMARY KEY (EKYC_ID)
);

CREATE TABLE OTP (
   OTP_ID varchar(10) NOT NULL,
   USER_ID varchar(10),
   CODE varchar(10),
   PURPOSE text,
   CREATED_AT datetime,
   EXPIRES_AT datetime,
   IS_USED bool,
   PRIMARY KEY (OTP_ID)
);

CREATE TABLE SAVING_DETAIL (
   SAVING_ACC_ID varchar(10) NOT NULL,
   ACCOUNT_ID varchar(10),
   PRINCIPAL_AMOUNT float,
   INTEREST_RATE float,
   TERM_MONTHS int,
   START_DATE datetime,
   MATURITY_DATE datetime,
   PRIMARY KEY (SAVING_ACC_ID)
);

CREATE TABLE MORTAGE_DETAIL (
   MORTAGE_ACC_ID varchar(10) NOT NULL,
   ACCOUNT_ID varchar(10),
   TOTAL_LOAN_AMOUNT float,
   REMAINING_BALANCE float,
   PAYMEN_FREQUENCY varchar(20),
   PAYMENT_AMOUNT float,
   NEXT_PAYMENT_DATE datetime,
   LOAN_END_DATE datetime,
   PRIMARY KEY (MORTAGE_ACC_ID)
);

CREATE TABLE TRANSACTION (
   TRANSACTION_ID varchar(10) NOT NULL,
   PAYMENT_ID varchar(10),
   ACCOUNT_ID varchar(10),
   AMOUNT float,
   CURRENCY varchar(100),
   ACCOUNT_TYPE text,
   STATUS text,
   CREATED_AT datetime,
   COMPLETE_AT datetime,
   DEST_ACC_NUM varchar(20),
   DEST_ACC_NAME text,
   DEST_BANK_CODE varchar(20),
   TYPE text,
   PRIMARY KEY (TRANSACTION_ID)
);

CREATE TABLE BILL (
   BILL_ID varchar(10) NOT NULL,
   PROVIDER varchar(100),
   AMOUNT_DUE datetime,
   STATUS text,
   DUE_DATE datetime,
   CREATED_AT datetime,
   PRIMARY KEY (BILL_ID)
);

CREATE TABLE BILL_PAYMENT (
   PAYMENT_ID varchar(10) NOT NULL,
   TRANSACTION_ID varchar(10),
   BILL_ID varchar(10),
   PAID_AT datetime,
   PRIMARY KEY (PAYMENT_ID)
);

CREATE TABLE UTILITY_PAYMENT (
   UTILITY_PAYMENT_ID varchar(10) NOT NULL,
   TRANSACTION_ID varchar(10),
   PROVIDER_CODE varchar(50),
   REFERENCE_CODE_1 varchar(100),
   REFERENCE_CODE_2 varchar(100),
   CREATED_AT datetime,
   PRIMARY KEY (UTILITY_PAYMENT_ID)
);

CREATE TABLE LOCATION (
   BRANCH_ID varchar(10) NOT NULL,
   NAME text,
   ADDRESS text,
   LAT float,
   LNG float,
   OPEN_HOURS varchar(30),
   CREATED_AT datetime,
   PRIMARY KEY (BRANCH_ID)
);

CREATE TABLE USER_BIOMETRIC (
   USER_ID varchar(10),
   BIOMETRIC_ID varchar(10),
   FACE_TEMPLATE_HASH text,
   DEVICE_BIOMETRIC bool,
   FACE_ENABLED bool,
   CREATED_AT datetime
);

ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACCOUNT_USER
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);

ALTER TABLE EKYC ADD CONSTRAINT FK_EKYC_USER
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);

ALTER TABLE OTP ADD CONSTRAINT FK_OTP_USER
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);

ALTER TABLE SAVING_DETAIL ADD CONSTRAINT FK_SAVING_ACCOUNT
FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);

ALTER TABLE MORTAGE_DETAIL ADD CONSTRAINT FK_MORTAGE_ACCOUNT
FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);

ALTER TABLE TRANSACTION ADD CONSTRAINT FK_TRANSACTION_ACCOUNT
FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);

ALTER TABLE BILL_PAYMENT ADD CONSTRAINT FK_BILLPAY_TRANSACTION
FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTION(TRANSACTION_ID);

ALTER TABLE BILL_PAYMENT ADD CONSTRAINT FK_BILLPAY_BILL
FOREIGN KEY (BILL_ID) REFERENCES BILL(BILL_ID);

ALTER TABLE UTILITY_PAYMENT ADD CONSTRAINT FK_UTILITY_TRANSACTION
FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTION(TRANSACTION_ID);

ALTER TABLE USER_BIOMETRIC ADD CONSTRAINT FK_USERBIO_USER
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);
