/*==============================================================*/
/* DBMS name:      MySQL 5.0                                    */
/* Created on:     06/12/2025                                   */
/*==============================================================*/

/*================== Table: USER_BIOMETRIC =====================*/
CREATE TABLE USER_BIOMETRIC (
    BIOMETRIC_ID varchar(10) NOT NULL,
    USER_ID varchar(10),
    FACE_TEMPLATE_HASH text,
    DEVICE_BIOMETRIC bool,
    FACE_ENABLED bool,
    CREATED_AT datetime,
    PRIMARY KEY (BIOMETRIC_ID)
);

/*================== Table: USER ================================*/
CREATE TABLE USER (
    USER_ID varchar(10) NOT NULL,
    BIOMETRIC_ID varchar(10),
    EKYC_ID varchar(10),
    FULL_NAME text,
    EMAIL text,
    PHONE text,
    ROLE text,
    CREATED_AT datetime,
    PASSWORD text,
    PRIMARY KEY (USER_ID)
);

/*================== Table: EKYC ================================*/
CREATE TABLE EKYC (
    EKYC_ID varchar(10) NOT NULL,
    USER_ID varchar(10),
    IMG_FRONT_URL text,
    IMG_BACK_URL text,
    SELFIE_URL text,
    STATUS text,
    REVIEWED_AT varchar(30),
    REVIEWED_BY varchar(30),
    CREATED_AT datetime,
    PRIMARY KEY (EKYC_ID)
);

/*================== Table: ACCOUNT =============================*/
CREATE TABLE ACCOUNT (
    ACCOUNT_ID varchar(10) NOT NULL,
    MORTAGE_ACC_ID varchar(10),
    USER_ID varchar(10),
    SAVING_ACC_ID varchar(10),
    ACCOUNT_TYPE text,
    BALANCE float,
    INTEREST_RATE float,
    CREATED_AT datetime,
    STATUS text,
    ACCOUNT_NUMBER text,
    PRIMARY KEY (ACCOUNT_ID)
);

/*================== Table: SAVING_DETAIL =======================*/
CREATE TABLE SAVING_DETAIL (
    SAVING_ACC_ID varchar(10) NOT NULL,
    ACCOUNT_ID varchar(10),
    PRINCIPAL_AMOUNT float,
    INTEREST_RATE float,
    TERM_MONTHS int,
    START_DATE datetime,
    MATURITY_DATE datetime,
    PRIMARY KEY (SAVING_ACC_ID)
);

/*================== Table: MORTAGE_DETAIL ======================*/
CREATE TABLE MORTAGE_DETAIL (
    MORTAGE_ACC_ID varchar(10) NOT NULL,
    ACCOUNT_ID varchar(10),
    TOTAL_LOAN_AMOUNT float,
    REMAINING_BALANCE float,
    PAYMEN_FREQUENCY varchar(20),
    PAYMENT_AMOUNT float,
    NEXT_PAYMENT_DATE datetime,
    LOAN_END_DATE datetime,
    PRIMARY KEY (MORTAGE_ACC_ID)
);

/*================== Table: TRANSACTION =========================*/
CREATE TABLE TRANSACTION (
    TRANSACTION_ID varchar(10) NOT NULL,
    PAYMENT_ID varchar(10),
    ACCOUNT_ID varchar(10),
    AMOUNT float,
    CURRENCY varchar(100),
    ACCOUNT_TYPE text,
    STATUS text,
    CREATED_AT datetime,
    COMPLETE_AT datetime,
    DEST_ACC_NUM varchar(20),
    DEST_ACC_NAME text,
    DEST_BANK_CODE varchar(20),
    TYPE text,
    PRIMARY KEY (TRANSACTION_ID)
);

/*================== Table: BILL ================================*/
CREATE TABLE BILL (
    BILL_ID varchar(10) NOT NULL,
    PROVIDER varchar(100),
    AMOUNT_DUE datetime,
    STATUS text,
    DUE_DATE datetime,
    CREATED_AT datetime,
    PRIMARY KEY (BILL_ID)
);

/*================== Table: BILL_PAYMENT ========================*/
CREATE TABLE BILL_PAYMENT (
    PAYMENT_ID varchar(10) NOT NULL,
    TRANSACTION_ID varchar(10),
    BILL_ID varchar(10),
    PAID_AT datetime,
    PRIMARY KEY (PAYMENT_ID)
);

/*================== Table: UTILITY_PAYMENT ====================*/
CREATE TABLE UTILITY_PAYMENT (
    UTILITY_PAYMENT_ID varchar(10) NOT NULL,
    TRANSACTION_ID varchar(10),
    PROVIDER_CODE varchar(50),
    REFERENCE_CODE_1 varchar(100),
    REFERENCE_CODE_2 varchar(100),
    CREATED_AT datetime,
    PRIMARY KEY (UTILITY_PAYMENT_ID)
);

/*================== Table: OTP =================================*/
CREATE TABLE OTP (
    OTP_ID varchar(10) NOT NULL,
    USER_ID varchar(10),
    CODE varchar(10),
    PURPOSE text,
    CREATED_AT datetime,
    EXPIRES_AT datetime,
    IS_USED bool,
    PRIMARY KEY (OTP_ID)
);

/*================== Table: REFRESH_TOKEN ======================*/
CREATE TABLE REFRESH_TOKEN (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID varchar(10) NOT NULL,
    TOKEN text NOT NULL,
    CREATED_AT datetime NOT NULL,
    EXPIRES_AT datetime NOT NULL,
    REVOKED bool DEFAULT 0
);

/*================== Table: TOKEN_BLACKLIST ====================*/
CREATE TABLE TOKEN_BLACKLIST (
    TOKEN_ID varchar(10) NOT NULL,
    TOKEN text,
    BLACKLISTED_AT datetime,
    PRIMARY KEY (TOKEN_ID)
);

/*================== Table: LOCATION ============================*/
CREATE TABLE LOCATION (
    BRANCH_ID varchar(10) NOT NULL,
    NAME text,
    ADDRESS text,
    LAT float,
    LNG float,
    OPEN_HOURS varchar(30),
    CREATED_AT datetime,
    PRIMARY KEY (BRANCH_ID)
);

/*================== Table: EXTERNAL_ACCOUNT ===================*/
CREATE TABLE EXTERNAL_ACCOUNT (
    EX_ACC_ID varchar(10) NOT NULL,
    BANK_CODE text,
    ACCOUNT_NUMBER text,
    ACCOUNT_NAME text,
    PRIMARY KEY (EX_ACC_ID)
);

/*================== FOREIGN KEY CONSTRAINTS ===================*/
ALTER TABLE USER ADD CONSTRAINT FK_USER_USER_BIOM_USER_BIO FOREIGN KEY (BIOMETRIC_ID)
    REFERENCES USER_BIOMETRIC(BIOMETRIC_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE USER ADD CONSTRAINT FK_USER_USER_EKYC_EKYC FOREIGN KEY (EKYC_ID)
    REFERENCES EKYC(EKYC_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACCOUNT_ACCOUNT_M_MORTAGE_ FOREIGN KEY (MORTAGE_ACC_ID)
    REFERENCES MORTAGE_DETAIL(MORTAGE_ACC_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACCOUNT_ACCOUNT_S_SAVING_D FOREIGN KEY (SAVING_ACC_ID)
    REFERENCES SAVING_DETAIL(SAVING_ACC_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACCOUNT_USER_ACCO_USER FOREIGN KEY (USER_ID)
    REFERENCES USER(USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE SAVING_DETAIL ADD CONSTRAINT FK_SAVING_D_ACCOUNT_S_ACCOUNT FOREIGN KEY (ACCOUNT_ID)
    REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MORTAGE_DETAIL ADD CONSTRAINT FK_MORTAGE__ACCOUNT_M_ACCOUNT FOREIGN KEY (ACCOUNT_ID)
    REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TRANSACTION ADD CONSTRAINT FK_TRANSACT_ACCOUNT_T_ACCOUNT FOREIGN KEY (ACCOUNT_ID)
    REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TRANSACTION ADD CONSTRAINT FK_TRANSACT_TRANSAC_P_BILL_PAY FOREIGN KEY (PAYMENT_ID)
    REFERENCES BILL_PAYMENT(PAYMENT_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BILL_PAYMENT ADD CONSTRAINT FK_BILL_PAY_BILL_BILL_BILL FOREIGN KEY (BILL_ID)
    REFERENCES BILL(BILL_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BILL_PAYMENT ADD CONSTRAINT FK_BILL_PAY_TRANSAC_P_TRANSACT FOREIGN KEY (TRANSACTION_ID)
    REFERENCES TRANSACTION(TRANSACTION_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE UTILITY_PAYMENT ADD CONSTRAINT FK_UTILITY__TRANSAC_U_TRANSACT FOREIGN KEY (TRANSACTION_ID)
    REFERENCES TRANSACTION(TRANSACTION_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE OTP ADD CONSTRAINT FK_OTP_USER_OTP_USER FOREIGN KEY (USER_ID)
    REFERENCES USER(USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE REFRESH_TOKEN ADD CONSTRAINT FK_REFRESH_USER FOREIGN KEY (USER_ID)
    REFERENCES USER(USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

